version: '3.7'
services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx.docker
      args:
        DOMAIN_NAME: ${DOCKER_NGINX_DOMAIN_NAME}
    depends_on:
      - php-fpm
      - ${DB_HOST}
      - redis
      - node
    volumes:
      - ./:/var/www
      - ./storage/docker/nginx:/var/log/nginx
    ports:
      - "${HTTP_PORT_DOCKER}:${HTTP_PORT}"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: ./docker/php-fpm.docker
    user: "${LINUX_UID}:${LINUX_GID}"
    volumes:
      - ./:/var/www
    links:
      - ${DB_HOST}
      - redis
    environment:
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: redis
  mysql:
    build:
      context: ./
      dockerfile: ./docker/mysql.docker
      args:
        MYSQL_DATABASES: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
    user: "${LINUX_UID}:${LINUX_GID}"
    ports:
      - "${DB_PORT_DOCKER}:${DB_PORT}"
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASES: ${DB_DATABASE}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - ${DB_HOST}
    ports:
      - ${PMA_DOCKER_PORT}:${PMA_PORT}
    links:
      - ${DB_HOST}
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 200000000
    restart: always
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT_DOCKER}:${REDIS_PORT}"
  node:
    build:
      context: ./
      dockerfile: ./docker/node.docker
    user: "${LINUX_UID}:${LINUX_GID}"
    volumes:
      - ./:/var/www
    tty: true
  swagger:
    image: swaggerapi/swagger-ui:latest
    ports:
      - ${SWAGGER_PORT_DOCKER}:${SWAGGER_PORT}
    environment:
      SWAGGER_JSON: ${SWAGGER_FILE}
    volumes:
      - ${SWAGGER_VOLUME_LOCAL_DIRECTORY}:${SWAGGER_VOLUME_DOCKER_DIRECTORY}